backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "blog/images" # Media files will be stored in the repo under blog/images
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI - as in, this is the label the cms editor will see
    folder: "blog" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Page Title", name: "title", widget: "string"} # Widgets define the data type and interface for entry fields
      - {label: "Post Title", name: "postTitle", widget: "string"} # https://www.netlifycms.org/docs/widgets/
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image Alt Text", name: "imageAlt", widget: "string"}