backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

site_url: https://condescending-feynman-61da7f.netlify.app/

# This line should *not* be indented
media_folder: "static/images" # Media files will be stored in the public folder
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI - as in, this is the label the cms editor will see
    folder: "blog" # The path to the folder where the documents are stored
    extension: html # determines the file extension searched for when finding existing entries in a folder collection and it determines the file extension used to save new collection items
    create: true # Allow users to create new documents in this collection
    delete: true # prevents user from deleting items in collection
    fields: # The fields for each document, usually in front matter
      - {label: "Page Title", name: "title", widget: "string"} # Widgets define the data type and interface for entry fields
      - {label: "Post Title", name: "postTitle", widget: "string"} # https://www.netlifycms.org/docs/widgets/
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image Alt Text", name: "imageAlt", widget: "string"}