backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true # to run local back end: npx netlify-cms-proxy-server

site_url: https://condescending-feynman-61da7f.netlify.app/

# This line should *not* be indented
media_folder: "static/images" # Media files will be stored in the public folder
collections:
  - label: "Blog" # Used in the UI - as in, this is the label the cms editor will see
    name: "blog" # Used in routes, e.g., /admin/collections/blog
    folder: "blog" # The path to the folder where the documents are stored
    extension: html # determines the file extension searched for when finding existing entries in a folder collection and it determines the file extension used to save new collection items
    create: true # Allow users to create new documents in this collection
    delete: true # prevents user from deleting items in collection
    fields: # The fields for each document, usually in front matter
      - {label: "Page Title", name: "title", widget: "string"} # Widgets define the data type and interface for entry fields
      - {label: "Post Title", name: "postTitle", widget: "string"} # https://www.netlifycms.org/docs/widgets/
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Image Alt Text", name: "imageAlt", widget: "string"}
      - {label: 'Map', name: 'geometry', widget: 'map', default: '{"type":"Point","coordinates":[-117.3981482,49.4833842]}'} # will default to position given when creating new content
  - label: "Pages"
    name: "pages"
    files:
      - label: "Site Settings"
        name: "settings"
        file: "_data/settings.json"
        fields:
        - {label: "About", name: "about", widget: "string"}
        - {label: "Banner", name: "banner", widget: "image", required: false }